#created by sai on 24th aug, 2020

name: "Hello world"
description : "Greet someone and record the time"
inputs:
  who-to-greet: #id of input
    description : "Who to greet"
    required : true
    default : "World"
outputs:
  time: #id of output
runs:
  using : "docker"
  image : "Dockerfile"
  args:
   - ${{ inputs.who-to-greet}}

   #Github will build an image from your 'Dockerfile', and run commands in a new container using this image.




